name: Coverage Badge
on:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js 12
        uses: actions/setup-node@master
        with:
          node-version: '12'
      - name: Generate coverage file
        run: |
          npm install
          npm run report
          mkdir -p .github/badges
      - name: Check test coverage
        id: test-coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "50"
          filename: "__coverage__/clover.xml"
      - name: Badge
        uses: emibcn/badge-action@v1
        with:
          label: 'Test coverage'
          status: '${{ steps.test-coverage.outputs.coverage }}'
          color: 'blue,555,daf'
          path: '.github/badges/coverage.svg'
      - name: Upload badge as artifact
        uses: actions/upload-artifact@v2
        with:
          name: badge
          path: '.github/badges/coverage.svg'
          if-no-files-found: error
      - name: Commit badge
        continue-on-error: true
        env:
          BADGE: ${{ steps.coverage.outputs.path }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${BADGE}"
          git commit -m "Add/Update badge"
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: coverage-badge
      