name: CI
on: push
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Test
        run: |
          npm install
          npm run-script lint
          npm run-script test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js 12
        uses: actions/setup-node@master
        with:
          node-version: '12'
      - name: build
        run: |
          npm install
          npm run-script prepublish